# Generated by Django 2.2 on 2020-03-18 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stdent',
            new_name='Student',
        ),
    ]
