# Generated by Django 3.0.4 on 2020-03-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoten', models.CharField(max_length=30)),
                ('tuoi', models.IntegerField(default=10)),
                ('gioitinh', models.CharField(max_length=5)),
            ],
        ),
    ]
